root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["-env", ".env.dev"]
  bin = "./tmp/api-debug"
  cmd = "go build -race -gcflags='-N -l' -ldflags='-X main.version=dev-debug' -o ./tmp/api-debug ./cmd/api"
  delay = 500
  exclude_dir = [
    "vendor",
    "tmp",
    "logs",
    "bin",
    "deployments",
    "bruno-collection",
    "docs",
    "testdata",
    "test_reports",
    "tests",
    ".git",
    ".github",
    ".vscode",
    "certs"
  ]
  exclude_file = []
  exclude_regex = ["_test\\.go$", "\\.test$", "\\.sarif$"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = [
    "internal",
    "cmd/api",
    "proto",
    "api"
  ]
  include_ext = ["go", "proto", "sql", "yaml", "toml", "json"]
  include_file = [".env.dev", ".env.api-dev"]
  kill_delay = "3s"
  log = "tmp/build-errors-debug.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 100
  send_interrupt = true
  stop_on_root = false

[color]
  app = "red"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = false
