// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: health.sql

package store

import (
	"context"
)

const getSystemHealth = `-- name: GetSystemHealth :one
SELECT
    'healthy' as status,
    NOW () as timestamp,
    current_database () as database_name,
    version () as database_version
`

type GetSystemHealthRow struct {
	Status          string      `db:"status" json:"status"`
	Timestamp       interface{} `db:"timestamp" json:"timestamp"`
	DatabaseName    string      `db:"database_name" json:"database_name"`
	DatabaseVersion string      `db:"database_version" json:"database_version"`
}

// EngLog Database Health Queries
// This file contains queries for health checking and system status
func (q *Queries) GetSystemHealth(ctx context.Context) (GetSystemHealthRow, error) {
	row := q.db.QueryRow(ctx, getSystemHealth)
	var i GetSystemHealthRow
	err := row.Scan(
		&i.Status,
		&i.Timestamp,
		&i.DatabaseName,
		&i.DatabaseVersion,
	)
	return i, err
}
