// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddTagToLogEntry(ctx context.Context, arg AddTagToLogEntryParams) error
	ArchiveInsight(ctx context.Context, arg ArchiveInsightParams) error
	CancelDeletionRequest(ctx context.Context, arg CancelDeletionRequestParams) error
	CancelTask(ctx context.Context, id uuid.UUID) error
	CleanupExpiredDenylistedTokens(ctx context.Context) error
	CleanupExpiredSessions(ctx context.Context) error
	CleanupOldInsights(ctx context.Context, createdAt pgtype.Timestamptz) error
	CleanupOldTasks(ctx context.Context, completedAt pgtype.Timestamptz) error
	CleanupUnusedTags(ctx context.Context) error
	CompleteTask(ctx context.Context, arg CompleteTaskParams) (Task, error)
	// EngLog Insights Management Queries
	// AI-generated insights and analytics
	CreateInsight(ctx context.Context, arg CreateInsightParams) (GeneratedInsight, error)
	// EngLog Log Entries Queries
	// Activity tracking and log entry management
	CreateLogEntry(ctx context.Context, arg CreateLogEntryParams) (LogEntry, error)
	// EngLog Project Management Queries
	// Project CRUD operations and statistics
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	// EngLog Authentication Queries
	// JWT token management and session handling
	CreateRefreshTokenDenylist(ctx context.Context, arg CreateRefreshTokenDenylistParams) error
	// EngLog Tags Management Queries
	// Tag CRUD operations and usage statistics
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	// EngLog Task Management Queries
	// Background task processing and job queue
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	// EngLog User Management Queries
	// User authentication and profile management
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error)
	DeactivateSession(ctx context.Context, id uuid.UUID) error
	DeactivateUserSessions(ctx context.Context, userID uuid.UUID) error
	DeleteInsight(ctx context.Context, arg DeleteInsightParams) error
	DeleteLogEntry(ctx context.Context, arg DeleteLogEntryParams) (int64, error)
	DeleteProject(ctx context.Context, arg DeleteProjectParams) error
	DeleteTag(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	FailTask(ctx context.Context, arg FailTaskParams) (Task, error)
	GetActiveProjectsByUser(ctx context.Context, createdBy uuid.UUID) ([]Project, error)
	GetActiveSessionsByUser(ctx context.Context, userID uuid.UUID) ([]UserSession, error)
	GetActivityTypeDistribution(ctx context.Context, arg GetActivityTypeDistributionParams) ([]GetActivityTypeDistributionRow, error)
	GetAllTags(ctx context.Context) ([]Tag, error)
	GetComparisonStats(ctx context.Context, arg GetComparisonStatsParams) (GetComparisonStatsRow, error)
	GetDailyActivityPattern(ctx context.Context, arg GetDailyActivityPatternParams) ([]DailyActivityPattern, error)
	GetDailyProductivityStats(ctx context.Context, arg GetDailyProductivityStatsParams) ([]GetDailyProductivityStatsRow, error)
	GetDenylistedTokensByUser(ctx context.Context, userID uuid.UUID) ([]RefreshTokenDenylist, error)
	GetHighValueEntries(ctx context.Context, arg GetHighValueEntriesParams) ([]LogEntry, error)
	GetImpactLevelDistribution(ctx context.Context, arg GetImpactLevelDistributionParams) ([]GetImpactLevelDistributionRow, error)
	GetInsightByID(ctx context.Context, id uuid.UUID) (GeneratedInsight, error)
	GetInsightGenerationMetrics(ctx context.Context, arg GetInsightGenerationMetricsParams) ([]GetInsightGenerationMetricsRow, error)
	GetInsightStats(ctx context.Context, userID uuid.UUID) (GetInsightStatsRow, error)
	GetInsightsByPeriod(ctx context.Context, arg GetInsightsByPeriodParams) ([]GeneratedInsight, error)
	GetInsightsByQuality(ctx context.Context, arg GetInsightsByQualityParams) ([]GeneratedInsight, error)
	GetInsightsByUser(ctx context.Context, arg GetInsightsByUserParams) ([]GeneratedInsight, error)
	GetInsightsByUserAndType(ctx context.Context, arg GetInsightsByUserAndTypeParams) ([]GeneratedInsight, error)
	GetLatestInsightByType(ctx context.Context, arg GetLatestInsightByTypeParams) (GeneratedInsight, error)
	GetLogEntriesByProject(ctx context.Context, projectID pgtype.UUID) ([]LogEntry, error)
	GetLogEntriesByType(ctx context.Context, arg GetLogEntriesByTypeParams) ([]LogEntry, error)
	GetLogEntriesByUser(ctx context.Context, arg GetLogEntriesByUserParams) ([]LogEntry, error)
	GetLogEntriesByUserAndDateRange(ctx context.Context, arg GetLogEntriesByUserAndDateRangeParams) ([]LogEntry, error)
	GetLogEntriesByUserAndProject(ctx context.Context, arg GetLogEntriesByUserAndProjectParams) ([]LogEntry, error)
	GetLogEntriesForTag(ctx context.Context, tagID uuid.UUID) ([]LogEntry, error)
	GetLogEntriesWithTags(ctx context.Context, arg GetLogEntriesWithTagsParams) ([]GetLogEntriesWithTagsRow, error)
	GetLogEntryByID(ctx context.Context, id uuid.UUID) (LogEntry, error)
	GetMonthlyActivitySummary(ctx context.Context, arg GetMonthlyActivitySummaryParams) ([]GetMonthlyActivitySummaryRow, error)
	GetPendingTasks(ctx context.Context, limit int32) ([]Task, error)
	GetPopularTags(ctx context.Context, limit int32) ([]Tag, error)
	GetProductivityByDayOfWeek(ctx context.Context, arg GetProductivityByDayOfWeekParams) ([]GetProductivityByDayOfWeekRow, error)
	GetProductivityByHour(ctx context.Context, arg GetProductivityByHourParams) ([]GetProductivityByHourRow, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error)
	GetProjectPerformanceMetrics(ctx context.Context, projectOwner uuid.UUID) ([]ProjectPerformanceMetric, error)
	GetProjectStats(ctx context.Context, projectID pgtype.UUID) (GetProjectStatsRow, error)
	GetProjectsByUser(ctx context.Context, createdBy uuid.UUID) ([]Project, error)
	GetProjectsWithActivity(ctx context.Context, createdBy uuid.UUID) ([]GetProjectsWithActivityRow, error)
	GetRecentLogEntries(ctx context.Context, arg GetRecentLogEntriesParams) ([]GetRecentLogEntriesRow, error)
	GetRecentUsers(ctx context.Context, limit int32) ([]GetRecentUsersRow, error)
	GetRecentlyUsedTags(ctx context.Context, arg GetRecentlyUsedTagsParams) ([]GetRecentlyUsedTagsRow, error)
	GetScheduledDeletions(ctx context.Context) ([]ScheduledDeletion, error)
	GetSessionCount(ctx context.Context) (int64, error)
	GetStuckTasks(ctx context.Context) ([]Task, error)
	// EngLog Database Health Queries
	// This file contains queries for health checking and system status
	GetSystemHealth(ctx context.Context) (GetSystemHealthRow, error)
	GetTagByID(ctx context.Context, id uuid.UUID) (Tag, error)
	GetTagByName(ctx context.Context, name string) (Tag, error)
	GetTagUsageStats(ctx context.Context) (GetTagUsageStatsRow, error)
	GetTagsForLogEntry(ctx context.Context, logEntryID uuid.UUID) ([]Tag, error)
	GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error)
	GetTaskPerformanceMetrics(ctx context.Context, completedAt pgtype.Timestamptz) ([]GetTaskPerformanceMetricsRow, error)
	GetTaskQueue(ctx context.Context) ([]GetTaskQueueRow, error)
	GetTaskStats(ctx context.Context, createdAt pgtype.Timestamptz) (GetTaskStatsRow, error)
	GetTasksByType(ctx context.Context, taskType string) ([]Task, error)
	GetTasksByUser(ctx context.Context, arg GetTasksByUserParams) ([]Task, error)
	GetTopProjectsByTime(ctx context.Context, arg GetTopProjectsByTimeParams) ([]GetTopProjectsByTimeRow, error)
	GetUserActivitySummary(ctx context.Context, arg GetUserActivitySummaryParams) (GetUserActivitySummaryRow, error)
	// EngLog Analytics Queries
	// Advanced analytics and reporting
	GetUserActivitySummaryView(ctx context.Context, userID uuid.UUID) (UserActivitySummary, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserCount(ctx context.Context) (int64, error)
	GetUserDefaultProject(ctx context.Context, createdBy uuid.UUID) (Project, error)
	GetUserDeletionRequests(ctx context.Context, userID uuid.UUID) ([]ScheduledDeletion, error)
	GetUserProductivityTrend(ctx context.Context, arg GetUserProductivityTrendParams) ([]interface{}, error)
	GetUserSession(ctx context.Context, id uuid.UUID) (UserSession, error)
	GetUserSessionByToken(ctx context.Context, sessionTokenHash string) (UserSession, error)
	GetUserTagUsage(ctx context.Context, userID uuid.UUID) ([]GetUserTagUsageRow, error)
	GetUserTaskHistory(ctx context.Context, arg GetUserTaskHistoryParams) ([]Task, error)
	GetValueRatingDistribution(ctx context.Context, arg GetValueRatingDistributionParams) ([]GetValueRatingDistributionRow, error)
	GetWeeklyActivitySummary(ctx context.Context, arg GetWeeklyActivitySummaryParams) ([]GetWeeklyActivitySummaryRow, error)
	IsRefreshTokenDenylisted(ctx context.Context, jti string) (bool, error)
	RefreshUserActivitySummary(ctx context.Context) error
	RemoveTagFromLogEntry(ctx context.Context, arg RemoveTagFromLogEntryParams) error
	ResetStuckTasks(ctx context.Context) error
	ScheduleUserDeletion(ctx context.Context, arg ScheduleUserDeletionParams) (ScheduledDeletion, error)
	SearchLogEntries(ctx context.Context, arg SearchLogEntriesParams) ([]LogEntry, error)
	SearchTags(ctx context.Context, arg SearchTagsParams) ([]Tag, error)
	SetProjectAsDefault(ctx context.Context) error
	StartTaskProcessing(ctx context.Context, id uuid.UUID) (Task, error)
	SupersedeOldInsights(ctx context.Context, arg SupersedeOldInsightsParams) error
	UpdateDeletionStatus(ctx context.Context, arg UpdateDeletionStatusParams) error
	UpdateInsight(ctx context.Context, arg UpdateInsightParams) (GeneratedInsight, error)
	UpdateLogEntry(ctx context.Context, arg UpdateLogEntryParams) (LogEntry, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateSessionActivity(ctx context.Context, id uuid.UUID) error
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
